"""Build the privacy-safe portfolio notebook from aggregate artifacts."""

from __future__ import annotations

from pathlib import Path

import nbformat as nbf

ROOT = Path(__file__).resolve().parents[1]
DESTINATION = ROOT / "notebooks" / "airline_sentiment_analysis.ipynb"


def main() -> None:
    notebook = nbf.v4.new_notebook()
    notebook["metadata"]["kernelspec"] = {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    }
    notebook["cells"] = [
        nbf.v4.new_markdown_cell(
            "# Airline Sentiment Classification\n\n"
            "A privacy-safe view of the chronological benchmark. The raw tweets are not "
            "rendered in this notebook; aggregate evidence is generated by the reusable "
            "package under src/airline_sentiment."
        ),
        nbf.v4.new_code_cell(
            "import json\n"
            "from pathlib import Path\n\n"
            "import pandas as pd\n"
            "from IPython.display import Image, display\n\n"
            "ROOT = Path.cwd()\n"
            "if not (ROOT / 'outputs').exists():\n"
            "    ROOT = ROOT.parent\n"
            "METRICS = ROOT / 'outputs' / 'metrics'\n"
            "FIGURES = ROOT / 'outputs' / 'figures'"
        ),
        nbf.v4.new_markdown_cell(
            "## Protocol\n\n"
            "Exact duplicate IDs and duplicate text are removed first. The latest 20% of "
            "rows by timestamp form the final holdout. Candidate pipelines are selected "
            "using five-fold expanding-window macro F1 on the earlier period only. Only the "
            "selected model is evaluated on the holdout."
        ),
        nbf.v4.new_code_cell(
            "summary = json.loads((METRICS / 'evaluation_summary.json').read_text())\n"
            "comparison = pd.read_csv(METRICS / 'model_comparison.csv')\n"
            "display(pd.DataFrame([summary['holdout_metrics']]))\n"
            "display(comparison)"
        ),
        nbf.v4.new_markdown_cell("## Class-Level Performance"),
        nbf.v4.new_code_cell(
            "report = pd.read_csv(METRICS / 'classification_report.csv', index_col=0)\n"
            "uncertainty = pd.read_csv(METRICS / 'holdout_uncertainty.csv')\n"
            "author_slices = pd.read_csv(METRICS / 'generalization_slices.csv')\n"
            "display(report)\n"
            "display(uncertainty)\n"
            "display(author_slices)\n"
            "display(Image(filename=str(FIGURES / 'confusion_matrix.png')))"
        ),
        nbf.v4.new_markdown_cell(
            "## Interpretable Associations\n\n"
            "Positive coefficients indicate features associated with each predicted class. "
            "They describe model behavior, not causes of customer sentiment."
        ),
        nbf.v4.new_code_cell(
            "features = pd.read_csv(METRICS / 'top_features.csv')\n"
            "display(features.groupby('class').head(10))\n"
            "display(Image(filename=str(FIGURES / 'class_distribution.png')))"
        ),
        nbf.v4.new_markdown_cell(
            "## Limitations\n\n"
            "- The data covers roughly one week in February 2015.\n"
            "- A later-message holdout is stronger than a random split but does not prove "
            "generalization to current language, other platforms, or other industries.\n"
            "- Neutral sentiment remains materially harder to classify.\n"
            "- Some later-period messages come from authors observed during training; "
            "performance is therefore reported separately for unseen authors.\n"
            "- Public social-media labels can contain annotation and representation bias."
        ),
    ]
    DESTINATION.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(notebook, DESTINATION)
    print(f"Built {DESTINATION}")


if __name__ == "__main__":
    main()
